# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from wejam.v1 import wejam_pb2 as wejam_dot_v1_dot_wejam__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wejam/v1/wejam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeJamStub:
    """---------------------------------------------------------------------------
    服务
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/wejam.v1.WeJam/GetStatus',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.Status.FromString,
                _registered_method=True)
        self.GetLoginState = channel.unary_unary(
                '/wejam.v1.WeJam/GetLoginState',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.GetLoginStateRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.LoginState.FromString,
                _registered_method=True)
        self.WatchLogin = channel.unary_stream(
                '/wejam.v1.WeJam/WatchLogin',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.WatchLoginRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.LoginState.FromString,
                _registered_method=True)
        self.GetLoginQRCode = channel.unary_unary(
                '/wejam.v1.WeJam/GetLoginQRCode',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.GetLoginQRCodeRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.LoginQRCode.FromString,
                _registered_method=True)
        self.SubmitLogin = channel.unary_unary(
                '/wejam.v1.WeJam/SubmitLogin',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.SubmitLoginRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.LoginState.FromString,
                _registered_method=True)
        self.ListChats = channel.unary_unary(
                '/wejam.v1.WeJam/ListChats',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.ListChatsRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.ListChatsResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/wejam.v1.WeJam/ListMessages',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.WatchMessages = channel.unary_stream(
                '/wejam.v1.WeJam/WatchMessages',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.WatchMessagesRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.MessageEvent.FromString,
                _registered_method=True)
        self.SendText = channel.unary_unary(
                '/wejam.v1.WeJam/SendText',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.SendTextRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.SendResult.FromString,
                _registered_method=True)
        self.InvokeMessage = channel.unary_unary(
                '/wejam.v1.WeJam/InvokeMessage',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.InvokeMessageRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.InvokeMessageResult.FromString,
                _registered_method=True)
        self.GetMessageSender = channel.unary_unary(
                '/wejam.v1.WeJam/GetMessageSender',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.GetMessageSenderRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.MessageSender.FromString,
                _registered_method=True)
        self.GetBadges = channel.unary_unary(
                '/wejam.v1.WeJam/GetBadges',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.GetBadgesRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.GetBadgesResponse.FromString,
                _registered_method=True)
        self.ListWindows = channel.unary_unary(
                '/wejam.v1.WeJam/ListWindows',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.ListWindowsRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.ListWindowsResponse.FromString,
                _registered_method=True)
        self.OpenWindow = channel.unary_unary(
                '/wejam.v1.WeJam/OpenWindow',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.OpenWindowRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.WindowResult.FromString,
                _registered_method=True)
        self.CloseWindow = channel.unary_unary(
                '/wejam.v1.WeJam/CloseWindow',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.CloseWindowRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.WindowResult.FromString,
                _registered_method=True)
        self.DumpA11yTree = channel.unary_unary(
                '/wejam.v1.WeJam/DumpA11yTree',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.DumpA11yTreeRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.DumpA11yTreeResponse.FromString,
                _registered_method=True)
        self.InvokeNode = channel.unary_unary(
                '/wejam.v1.WeJam/InvokeNode',
                request_serializer=wejam_dot_v1_dot_wejam__pb2.InvokeNodeRequest.SerializeToString,
                response_deserializer=wejam_dot_v1_dot_wejam__pb2.InvokeNodeResponse.FromString,
                _registered_method=True)


class WeJamServicer:
    """---------------------------------------------------------------------------
    服务
    ---------------------------------------------------------------------------
    """

    def GetStatus(self, request, context):
        """服务与微信进程的整体状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoginState(self, request, context):
        """---- 登录：状态由服务维护，客户端只消费 ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoginQRCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitLogin(self, request, context):
        """「记住账号」场景下由客户端触发；服务内部决定怎么落地
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChats(self, request, context):
        """---- 会话与消息 ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchMessages(self, request, context):
        """轮询式增量推送：服务端自己 diff，客户端不做任何解析。
        建议**显式指定 chat**：指定后服务端会保持该会话打开，无歧义。
        不指定时跟随「当前打开的会话」，此时若界面切走，
        切换瞬间到达的消息可能被计入新基线而漏推 —— 这是界面语义的固有歧义。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeMessage(self, request, context):
        """对某条消息执行右键菜单动作（复制 / 转发 / 收藏 / 引用 / 提醒 / 翻译 / 多选）。
        删除与撤回属于危险动作，服务端默认拒绝。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageSender(self, request, context):
        """取某条消息的发送者（群昵称）。
        消息列表项在无障碍树里没有发送者节点，服务端通过「点发送者头像 →
        读资料卡」获得。每次约 1.5~2 秒，适合按需查询而非整屏批量。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBadges(self, request, context):
        """---- 未读徽标 ----
        说明：导航图标上的「小红点/数字徽标」是**绘制装饰**，不在无障碍树里。
        服务端用「无障碍定位 + 像素颜色判定」给出「有没有徽标」；
        徽标里的数字不 OCR 读不到，但会话级未读数可由 ListChats 精确获得。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWindows(self, request, context):
        """---- 独立聊天窗口 ----
        把会话开进自己的窗口。价值：主窗口里切换会话要 3~7 秒，而会话已经在
        眼前时只要 0.7~1 秒。**读取可以多窗口并行**（a11y 不依赖焦点），
        但**写入仍然串行** —— X11 只有一个键盘焦点。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpA11yTree(self, request, context):
        """---- 逃生舱：给需要深度定制的客户端，默认可由服务开关关闭 ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeJamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.GetStatusRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.Status.SerializeToString,
            ),
            'GetLoginState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoginState,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.GetLoginStateRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.LoginState.SerializeToString,
            ),
            'WatchLogin': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLogin,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.WatchLoginRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.LoginState.SerializeToString,
            ),
            'GetLoginQRCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoginQRCode,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.GetLoginQRCodeRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.LoginQRCode.SerializeToString,
            ),
            'SubmitLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitLogin,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.SubmitLoginRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.LoginState.SerializeToString,
            ),
            'ListChats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChats,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.ListChatsRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.ListChatsResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.ListMessagesRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.ListMessagesResponse.SerializeToString,
            ),
            'WatchMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchMessages,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.WatchMessagesRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.MessageEvent.SerializeToString,
            ),
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.SendTextRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.SendResult.SerializeToString,
            ),
            'InvokeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeMessage,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.InvokeMessageRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.InvokeMessageResult.SerializeToString,
            ),
            'GetMessageSender': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageSender,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.GetMessageSenderRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.MessageSender.SerializeToString,
            ),
            'GetBadges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBadges,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.GetBadgesRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.GetBadgesResponse.SerializeToString,
            ),
            'ListWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWindows,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.ListWindowsRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.ListWindowsResponse.SerializeToString,
            ),
            'OpenWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenWindow,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.OpenWindowRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.WindowResult.SerializeToString,
            ),
            'CloseWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseWindow,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.CloseWindowRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.WindowResult.SerializeToString,
            ),
            'DumpA11yTree': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpA11yTree,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.DumpA11yTreeRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.DumpA11yTreeResponse.SerializeToString,
            ),
            'InvokeNode': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeNode,
                    request_deserializer=wejam_dot_v1_dot_wejam__pb2.InvokeNodeRequest.FromString,
                    response_serializer=wejam_dot_v1_dot_wejam__pb2.InvokeNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wejam.v1.WeJam', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wejam.v1.WeJam', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeJam:
    """---------------------------------------------------------------------------
    服务
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/GetStatus',
            wejam_dot_v1_dot_wejam__pb2.GetStatusRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoginState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/GetLoginState',
            wejam_dot_v1_dot_wejam__pb2.GetLoginStateRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.LoginState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wejam.v1.WeJam/WatchLogin',
            wejam_dot_v1_dot_wejam__pb2.WatchLoginRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.LoginState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoginQRCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/GetLoginQRCode',
            wejam_dot_v1_dot_wejam__pb2.GetLoginQRCodeRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.LoginQRCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/SubmitLogin',
            wejam_dot_v1_dot_wejam__pb2.SubmitLoginRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.LoginState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/ListChats',
            wejam_dot_v1_dot_wejam__pb2.ListChatsRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.ListChatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/ListMessages',
            wejam_dot_v1_dot_wejam__pb2.ListMessagesRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wejam.v1.WeJam/WatchMessages',
            wejam_dot_v1_dot_wejam__pb2.WatchMessagesRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.MessageEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/SendText',
            wejam_dot_v1_dot_wejam__pb2.SendTextRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.SendResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/InvokeMessage',
            wejam_dot_v1_dot_wejam__pb2.InvokeMessageRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.InvokeMessageResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessageSender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/GetMessageSender',
            wejam_dot_v1_dot_wejam__pb2.GetMessageSenderRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.MessageSender.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBadges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/GetBadges',
            wejam_dot_v1_dot_wejam__pb2.GetBadgesRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.GetBadgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/ListWindows',
            wejam_dot_v1_dot_wejam__pb2.ListWindowsRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.ListWindowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/OpenWindow',
            wejam_dot_v1_dot_wejam__pb2.OpenWindowRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.WindowResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/CloseWindow',
            wejam_dot_v1_dot_wejam__pb2.CloseWindowRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.WindowResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DumpA11yTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/DumpA11yTree',
            wejam_dot_v1_dot_wejam__pb2.DumpA11yTreeRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.DumpA11yTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wejam.v1.WeJam/InvokeNode',
            wejam_dot_v1_dot_wejam__pb2.InvokeNodeRequest.SerializeToString,
            wejam_dot_v1_dot_wejam__pb2.InvokeNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
